[package]
name    = "todo-app"
version.workspace = true
edition.workspace = true

[[bin]]
name = "todo-app"
path = "src/main.rs"

[dependencies]
di-core              = { path = "../../crates/di-core" }
di-macro             = { path = "../../crates/di-macro" }
kernway-core         = { workspace = true }
kernway-server       = { path = "../../crates/kernway-server" }
kernway-web          = { path = "../../crates/kernway-web" }
kernway-orm-core     = { path = "../../crates/kernway-orm-core" }
kernway-orm-macro    = { path = "../../crates/kernway-orm-macro" }
kernway-orm-memory   = { path = "../../crates/kernway-orm-memory" }
kernway-cache-core   = { path = "../../crates/kernway-cache-core" }
kernway-cache-memory = { path = "../../crates/kernway-cache-memory" }
kernway-openapi      = { path = "../../crates/kernway-openapi" }
kernway-sse          = { path = "../../crates/kernway-sse" }
serde                = { workspace = true }
serde_json           = { workspace = true }
