use std::fmt::Debug;
use serde::{de::DeserializeOwned, Serialize};
use std::hash::Hash;

/// Column type hint — used by macro-generated metadata.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ColumnType {
    /// 32-bit signed integer.
    Integer,
    /// 64-bit signed integer — what an auto-increment key normally maps to.
    BigInt,
    /// Variable-length text.
    Text,
    /// Boolean. Backends without a native type store it as 0/1.
    Boolean,
    /// Double-precision floating point. Not for money — use a decimal column.
    Float,
    /// Date and time.
    Timestamp,
    /// A JSON document, when the backend supports one.
    Json,
    /// The macro could not infer a type from the Rust field.
    ///
    /// Not an error — a backend falls back to its own default mapping.
    Unknown,
}

/// Column metadata — generated by the `#[entity]` macro.
#[derive(Debug, Clone)]
pub struct ColumnDef {
    /// Column name in the database.
    pub name: &'static str,
    /// Rust field name it maps to. Differs from `name` under
    /// `#[column(name = "...")]`.
    pub field: &'static str,
    /// Inferred column type.
    pub col_type: ColumnType,
    /// Whether the column accepts NULL — true for `Option<T>` fields.
    pub nullable: bool,
    /// Whether this is the primary key (`#[id]`).
    pub primary_key: bool,
    /// Whether a UNIQUE constraint applies.
    pub unique: bool,
    /// Whether the database supplies the value — auto-increment keys and
    /// managed timestamps. Such columns are omitted from INSERT statements.
    pub auto: bool,
}

/// The kind of association between two entities.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RelationKind {
    /// This entity holds a foreign key to one row of the target (belongs-to).
    ManyToOne,
    /// The target holds the foreign key; this entity has many of them.
    OneToMany,
    /// A one-to-one, this side holding the foreign key.
    OneToOne,
    /// A many-to-many through a join table.
    ManyToMany,
}

/// A declared association — **metadata only**. `kernway-orm-core` is the spec;
/// whether (and how) a driver acts on it is the driver's business: a relational
/// backend may enforce a foreign key and cascade on save/delete, while a
/// document or search backend (e.g. Meilisearch) ignores it and denormalises.
///
/// Loading itself stays explicit (Rust has no lazy proxies): fetch the related
/// rows with a derived finder (`find_by_user_id`) or a [`Spec`](crate::spec::Spec).
#[derive(Debug, Clone)]
pub struct RelationDef {
    /// The Rust field the relation is declared on.
    pub field: &'static str,
    /// The kind of association.
    pub kind: RelationKind,
    /// The related entity's table name.
    pub target_table: &'static str,
    /// The foreign-key column: on this entity for `ManyToOne`/`OneToOne`, on the
    /// target for `OneToMany` (its `mapped_by`).
    pub foreign_key: &'static str,
    /// The join table, for `ManyToMany` only.
    pub join_table: Option<&'static str>,
}

/// Marker trait for ORM-managed structs.
/// Equivalent to @Entity in JPA.
///
/// Implement this via the `#[entity]` macro — do not implement manually.
pub trait Entity: Send + Sync + Sized + Clone + Debug + 'static {
    /// The primary key type. A single `#[id]` field gives that field's type
    /// (e.g. `u64`, `String`); multiple `#[id]` fields give a **tuple** of them,
    /// in declaration order (a composite key, e.g. `(String, u32)`).
    type Id: Send + Sync + Clone + Eq + Hash + Debug + Serialize + DeserializeOwned + 'static;

    /// Database table name.
    fn table_name() -> &'static str;

    /// The entity's primary key, by value.
    ///
    /// Returned owned rather than by reference so a composite key can be built
    /// on the fly from several fields (there is no single tuple field to borrow).
    /// `Id: Clone` keeps this cheap for the usual small keys.
    fn id(&self) -> Self::Id;

    /// All column definitions — generated by the `#[entity]` macro.
    fn columns() -> &'static [ColumnDef];

    /// Declared associations — generated by the `#[entity]` macro from
    /// `#[many_to_one]` / `#[one_to_many]` / … field attributes. Empty by default;
    /// only relational drivers act on these (see [`RelationDef`]).
    fn relations() -> &'static [RelationDef] {
        &[]
    }
}
