use std::fmt::Debug;
use serde::{de::DeserializeOwned, Serialize};
use std::hash::Hash;

/// Column type hint — used by macro-generated metadata.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ColumnType {
    /// 32-bit signed integer.
    Integer,
    /// 64-bit signed integer — what an auto-increment key normally maps to.
    BigInt,
    /// Variable-length text.
    Text,
    /// Boolean. Backends without a native type store it as 0/1.
    Boolean,
    /// Double-precision floating point. Not for money — use a decimal column.
    Float,
    /// Date and time.
    Timestamp,
    /// A JSON document, when the backend supports one.
    Json,
    /// The macro could not infer a type from the Rust field.
    ///
    /// Not an error — a backend falls back to its own default mapping.
    Unknown,
}

/// Column metadata — generated by the `#[entity]` macro.
#[derive(Debug, Clone)]
pub struct ColumnDef {
    /// Column name in the database.
    pub name: &'static str,
    /// Rust field name it maps to. Differs from `name` under
    /// `#[column(name = "...")]`.
    pub field: &'static str,
    /// Inferred column type.
    pub col_type: ColumnType,
    /// Whether the column accepts NULL — true for `Option<T>` fields.
    pub nullable: bool,
    /// Whether this is the primary key (`#[id]`).
    pub primary_key: bool,
    /// Whether a UNIQUE constraint applies.
    pub unique: bool,
    /// Whether the database supplies the value — auto-increment keys and
    /// managed timestamps. Such columns are omitted from INSERT statements.
    pub auto: bool,
}

/// Marker trait for ORM-managed structs.
/// Equivalent to @Entity in JPA.
///
/// Implement this via the `#[entity]` macro — do not implement manually.
pub trait Entity: Send + Sync + Sized + Clone + Debug + 'static {
    /// The primary key type (e.g. u64, String, Uuid).
    type Id: Send + Sync + Clone + Eq + Hash + Debug + Serialize + DeserializeOwned + 'static;

    /// Database table name.
    fn table_name() -> &'static str;

    /// Returns a reference to the entity's primary key.
    fn id(&self) -> &Self::Id;

    /// All column definitions — generated by the `#[entity]` macro.
    fn columns() -> &'static [ColumnDef];
}
