use std::fmt::Debug;
use std::hash::Hash;

/// Column type hint — used by macro-generated metadata.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ColumnType {
    Integer,
    BigInt,
    Text,
    Boolean,
    Float,
    Timestamp,
    Json,
    Unknown,
}

/// Column metadata — generated by #[entity] macro.
#[derive(Debug, Clone)]
pub struct ColumnDef {
    pub name:        &'static str,
    pub field:       &'static str,
    pub col_type:    ColumnType,
    pub nullable:    bool,
    pub primary_key: bool,
    pub unique:      bool,
    pub auto:        bool,
}

/// Marker trait for ORM-managed structs.
/// Equivalent to @Entity in JPA.
///
/// Implement this via `#[entity]` macro — do not implement manually.
pub trait Entity: Send + Sync + Sized + Clone + Debug + 'static {
    /// The primary key type (e.g. u64, String, Uuid).
    type Id: Send + Sync + Clone + Eq + Hash + Debug + 'static;

    /// Database table name.
    fn table_name() -> &'static str;

    /// Returns a reference to the entity's primary key.
    fn id(&self) -> &Self::Id;

    /// All column definitions — generated by #[entity] macro.
    fn columns() -> &'static [ColumnDef];
}
