[package]
name        = "kernway-server"
description = "Kernway HTTP server — Router, KernwayApp builder"
version.workspace    = true
edition.workspace    = true
license.workspace    = true

[dependencies]
kernway-core = { workspace = true }
kernway-http = { workspace = true }
rt-net       = { workspace = true }
rt-core      = { workspace = true }
di-core      = { workspace = true }
thiserror    = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name    = "routing"
harness = false
