[package]
name        = "kernway-orm-memory"
description = "Kernway in-memory ORM implementation — for testing and prototyping"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kernway-orm-core = { path = "../kernway-orm-core" }
serde            = { workspace = true }
serde_json       = { workspace = true }

[dev-dependencies]
kernway-orm-macro = { path = "../kernway-orm-macro" }
