//! Marker traits generated by di-macro.

/// Marker trait for all `#[component]` beans.
/// Generated by the `#[component]` macro — users should not implement it manually.
pub trait KernwayComponent: Send + Sync + 'static {
    /// Component name (struct name).
    fn component_name() -> &'static str
    where
        Self: Sized;
}

/// Marker trait for `#[controller]` beans.
/// Generated by the `#[controller("/path")]` macro.
pub trait KernwayController: KernwayComponent {
    /// Controller route prefix.
    fn route_prefix() -> &'static str
    where
        Self: Sized;
}
