[package]
name        = "kernway"
description = "Kernway — Rust Web Framework (Spring-inspired)"
version.workspace    = true
edition.workspace    = true
authors.workspace    = true
license.workspace    = true
repository.workspace = true
homepage.workspace   = true

[dependencies]
kernway-core = { workspace = true }
di-core      = { workspace = true }
di-macro     = { workspace = true }
